### ISSUE TITLE
Not able to generate

### ISSUE THREAD

**Issue by luthis1124** [SicariusSicariiStuff/Diffusion_TTS#10] opened 2023-12-15 18:34 UTC
> Traceback (most recent call last):
> 
> File "oobabooga/extensions/Diffusion_TTS/script.py", line 289, in output_modifier
> 
> generate_audio(model, voice_samples, conditioning_latents, output_dir, output_file, gen_kwargs, texts)
> 
> File "oobabooga/extensions/Diffusion_TTS/script.py", line 325, in generate_audio
> 
> gen = tts.tts_with_preset(text, voice_samples=samples, conditioning_latents=latents, **gen_kwargs)
> 
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "oobabooga/extensions/Diffusion_TTS/tortoise/tortoise/api.py", line 353, in tts_with_preset
> 
> return self.tts(text, **settings)
> 
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "oobabooga/extensions/Diffusion_TTS/tortoise/tortoise/api.py", line 497, in tts
> 
> clip_results = torch.cat(clip_results, dim=0)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by luthis1124** [comment] 2023-12-15 18:37
And nothing in the ../tortoise/outputs folder

Generating autoregressive samples..
Hello! Im here to assist you with any questions or tasks you may have.
0it [00:00, ?it/s]
Computing best candidates using CLVP
0it [00:00, ?it/s]
Output generated in 1.12 seconds (36.64 tokens/s, 41 tokens, context 102, seed 1384729939)
Generating autoregressive samples..
Well, it looks like we are having a conversation!
0it [00:00, ?it/s]
Computing best candidates using CLVP
0it [00:00, ?it/s]

**Comment by luthis1124** [comment] 2023-12-15 18:47
I think I'm missing the logs that tell me actually why audio isn't generating.. the logs are only saying that there isn't audio clips to stitch together.

**Comment by SicariusSicariiStuff** [comment] 2023-12-18 15:30
Have you manage to resolve it or figure out what was the issue? I can't reproduce the bug

**Comment by SicariusSicariiStuff** [comment] 2024-01-28 13:29
as there were no replies, and i wasn't able to reproduce the bug, i am closing this issue.

**Closed as completed** 2024-01-28 13:30 UTC
